server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 15s
  write_timeout: 15s

database:
  url: "postgresql://bitcurrent:localdev@localhost:5432/bitcurrent?sslmode=disable"
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: 3600s
  max_conn_idle_time: 600s

redis:
  url: "redis://localhost:6379/0"
  password: ""
  pool_size: 10
  min_idle_conns: 2
  max_retries: 3

jwt:
  secret: "bitcurrent-dev-secret-change-in-production"
  issuer: "bitcurrent-api-gateway"
  expiry: 24h

logger:
  level: "info"
  environment: "development"
  output_paths:
    - "stdout"

rate_limit:
  requests_per_minute: 100
  burst: 20









