apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bitcurrent-starter
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 805694794171.dkr.ecr.eu-west-2.amazonaws.com/bitcurrent/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://aa566433839ec4bfe8113014ed98d8b9-1852355696.eu-west-2.elb.amazonaws.com"
        - name: NEXT_PUBLIC_WS_URL
          value: "ws://aa566433839ec4bfe8113014ed98d8b9-1852355696.eu-west-2.elb.amazonaws.com/ws"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bitcurrent-starter
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: frontend
