# BitCurrent Exchange - Alertmanager Configuration

global:
  resolve_timeout: 5m
  slack_api_url: 'SLACK_WEBHOOK_URL_HERE'

# Route tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts go to PagerDuty and Slack
    - match:
        severity: critical
      receiver: 'pagerduty-critical'
      continue: true
    
    - match:
        severity: critical
      receiver: 'slack-critical'
    
    # Warning alerts go to Slack
    - match:
        severity: warning
      receiver: 'slack-warnings'
    
    # Info alerts go to Slack (low priority channel)
    - match:
        severity: info
      receiver: 'slack-info'
    
    # Business alerts go to business team
    - match:
        component: business
      receiver: 'slack-business'
    
    # Security alerts go to security team
    - match:
        component: security
      receiver: 'slack-security'

# Inhibition rules (prevent alert spam)
inhibit_rules:
  # Inhibit all alerts if the entire service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['job']
  
  # Don't alert on high latency if matching engine is down
  - source_match:
      alertname: 'MatchingEngineDown'
    target_match:
      alertname: 'HighMatchingLatency'

# Receivers
receivers:
  - name: 'default'
    slack_configs:
      - channel: '#alerts'
        title: 'BitCurrent Alert'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'pagerduty-critical'
    pagerduty_configs:
      - service_key: 'PAGERDUTY_SERVICE_KEY_HERE'
        description: '{{ .CommonAnnotations.summary }}'
        severity: '{{ .CommonLabels.severity }}'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#alerts-critical'
        color: 'danger'
        title: '🚨 CRITICAL: {{ .CommonAnnotations.summary }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Component:* {{ .Labels.component }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        send_resolved: true

  - name: 'slack-warnings'
    slack_configs:
      - channel: '#alerts-warnings'
        color: 'warning'
        title: '⚠️  WARNING: {{ .CommonAnnotations.summary }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true

  - name: 'slack-info'
    slack_configs:
      - channel: '#alerts-info'
        color: 'good'
        title: 'ℹ️  INFO: {{ .CommonAnnotations.summary }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'slack-business'
    slack_configs:
      - channel: '#business-metrics'
        title: '📊 Business Alert: {{ .CommonAnnotations.summary }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'slack-security'
    slack_configs:
      - channel: '#security-alerts'
        color: 'danger'
        title: '🔒 Security Alert: {{ .CommonAnnotations.summary }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Description:* {{ .Annotations.description }}
          *User:* {{ .Labels.user_id }}
          *IP:* {{ .Labels.ip_address }}
          {{ end }}
        send_resolved: false



